#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Sample.CognitoSyncSettings.Android.Resource", IsApplication=true)]

namespace Sample.CognitoSyncSettings.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLStorage.Resource.String.ApplicationName = global::Sample.CognitoSyncSettings.Android.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::Sample.CognitoSyncSettings.Android.Resource.String.Hello;
			global::PCLCrypto.Resource.String.ApplicationName = global::Sample.CognitoSyncSettings.Android.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::Sample.CognitoSyncSettings.Android.Resource.String.Hello;
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::Sample.CognitoSyncSettings.Android.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::Sample.CognitoSyncSettings.Android.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::Sample.CognitoSyncSettings.Android.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::Sample.CognitoSyncSettings.Android.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::Sample.CognitoSyncSettings.Android.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::Sample.CognitoSyncSettings.Android.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::Sample.CognitoSyncSettings.Android.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::Sample.CognitoSyncSettings.Android.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::Sample.CognitoSyncSettings.Android.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::Sample.CognitoSyncSettings.Android.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::Sample.CognitoSyncSettings.Android.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::Sample.CognitoSyncSettings.Android.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::Sample.CognitoSyncSettings.Android.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::Sample.CognitoSyncSettings.Android.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::Sample.CognitoSyncSettings.Android.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::Sample.CognitoSyncSettings.Android.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::Sample.CognitoSyncSettings.Android.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::Sample.CognitoSyncSettings.Android.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::Sample.CognitoSyncSettings.Android.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::Sample.CognitoSyncSettings.Android.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::Sample.CognitoSyncSettings.Android.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::Sample.CognitoSyncSettings.Android.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::Sample.CognitoSyncSettings.Android.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::Sample.CognitoSyncSettings.Android.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::Sample.CognitoSyncSettings.Android.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::Sample.CognitoSyncSettings.Android.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::Sample.CognitoSyncSettings.Android.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::Sample.CognitoSyncSettings.Android.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::Sample.CognitoSyncSettings.Android.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::Sample.CognitoSyncSettings.Android.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::Sample.CognitoSyncSettings.Android.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::Sample.CognitoSyncSettings.Android.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::Sample.CognitoSyncSettings.Android.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::Sample.CognitoSyncSettings.Android.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::Sample.CognitoSyncSettings.Android.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::Sample.CognitoSyncSettings.Android.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::Sample.CognitoSyncSettings.Android.Resource.Styleable.ProgressWheel_ahTextSize;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0a0000
			public const int enum_preference_entries = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int enum_preference_entry_values = 2131361793;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000e
			public const int ahBarColor = 2130771982;
			
			// aapt resource value: 0x7f010016
			public const int ahBarLength = 2130771990;
			
			// aapt resource value: 0x7f010015
			public const int ahBarWidth = 2130771989;
			
			// aapt resource value: 0x7f010013
			public const int ahCircleColor = 2130771987;
			
			// aapt resource value: 0x7f010012
			public const int ahDelayMillis = 2130771986;
			
			// aapt resource value: 0x7f010014
			public const int ahRadius = 2130771988;
			
			// aapt resource value: 0x7f01000f
			public const int ahRimColor = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int ahRimWidth = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int ahSpinSpeed = 2130771985;
			
			// aapt resource value: 0x7f01000b
			public const int ahText = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int ahTextColor = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int ahTextSize = 2130771981;
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f01001b
			public const int com_facebook_auxiliary_view_position = 2130771995;
			
			// aapt resource value: 0x7f01001d
			public const int com_facebook_confirm_logout = 2130771997;
			
			// aapt resource value: 0x7f010017
			public const int com_facebook_foreground_color = 2130771991;
			
			// aapt resource value: 0x7f01001c
			public const int com_facebook_horizontal_alignment = 2130771996;
			
			// aapt resource value: 0x7f010022
			public const int com_facebook_is_cropped = 2130772002;
			
			// aapt resource value: 0x7f01001e
			public const int com_facebook_login_text = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int com_facebook_logout_text = 2130771999;
			
			// aapt resource value: 0x7f010018
			public const int com_facebook_object_id = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int com_facebook_object_type = 2130771993;
			
			// aapt resource value: 0x7f010021
			public const int com_facebook_preset_size = 2130772001;
			
			// aapt resource value: 0x7f01001a
			public const int com_facebook_style = 2130771994;
			
			// aapt resource value: 0x7f010020
			public const int com_facebook_tooltip_mode = 2130772000;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int cardview_dark_background = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int cardview_light_background = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int cardview_shadow_end_color = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int cardview_shadow_start_color = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int com_facebook_blue = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int com_facebook_button_background_color = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int com_facebook_button_background_color_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int com_facebook_button_background_color_focused = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int com_facebook_button_background_color_focused_disabled = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int com_facebook_button_background_color_pressed = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int com_facebook_button_background_color_selected = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int com_facebook_button_border_color_focused = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int com_facebook_button_login_silver_background_color = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int com_facebook_button_login_silver_background_color_pressed = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int com_facebook_button_send_background_color = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int com_facebook_button_send_background_color_pressed = 2131099663;
			
			// aapt resource value: 0x7f060016
			public const int com_facebook_button_text_color = 2131099670;
			
			// aapt resource value: 0x7f060010
			public const int com_facebook_device_auth_text = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int com_facebook_likeboxcountview_border_color = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int com_facebook_likeboxcountview_text_color = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int com_facebook_likeview_text_color = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int com_facebook_messenger_blue = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int com_facebook_send_button_text_color = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int com_facebook_share_button_text_color = 2131099669;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int cardview_compat_inset_shadow = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int cardview_default_elevation = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int cardview_default_radius = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int com_facebook_auth_dialog_corner_radius = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int com_facebook_auth_dialog_corner_radius_oversized = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int com_facebook_button_corner_radius = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int com_facebook_likeboxcountview_border_radius = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int com_facebook_likeboxcountview_border_width = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int com_facebook_likeboxcountview_caret_height = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int com_facebook_likeboxcountview_caret_width = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int com_facebook_likeboxcountview_text_padding = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int com_facebook_likeboxcountview_text_size = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int com_facebook_likeview_edge_padding = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int com_facebook_likeview_internal_padding = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int com_facebook_likeview_text_size = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int com_facebook_profilepictureview_preset_size_large = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int com_facebook_profilepictureview_preset_size_normal = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int com_facebook_profilepictureview_preset_size_small = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int com_facebook_share_button_compound_drawable_padding = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int com_facebook_share_button_padding_bottom = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int com_facebook_share_button_padding_left = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int com_facebook_share_button_padding_right = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int com_facebook_share_button_padding_top = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int com_facebook_share_button_text_size = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int com_facebook_tooltip_horizontal_padding = 2131165208;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int com_facebook_auth_dialog_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int com_facebook_auth_dialog_cancel_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int com_facebook_auth_dialog_header_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int com_facebook_button_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int com_facebook_button_icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int com_facebook_button_icon_blue = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int com_facebook_button_icon_white = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int com_facebook_button_like_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int com_facebook_button_like_icon_selected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int com_facebook_button_login_silver_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int com_facebook_button_send_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int com_facebook_button_send_icon_blue = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_facebook_button_send_icon_white = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_facebook_close = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_facebook_favicon_white = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_profile_picture_blank_portrait = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_profile_picture_blank_square = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_send_button_icon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int com_facebook_tooltip_black_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int com_facebook_tooltip_black_bottomnub = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int com_facebook_tooltip_black_topnub = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int com_facebook_tooltip_black_xout = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int com_facebook_tooltip_blue_background = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int com_facebook_tooltip_blue_bottomnub = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int com_facebook_tooltip_blue_topnub = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int com_facebook_tooltip_blue_xout = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_errorstatus = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_successstatus = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int messenger_bubble_large_blue = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int messenger_bubble_large_white = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int messenger_bubble_small_blue = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int messenger_bubble_small_white = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int messenger_button_blue_bg_round = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int messenger_button_blue_bg_selector = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int messenger_button_send_round_shadow = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int messenger_button_white_bg_round = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int messenger_button_white_bg_selector = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int roundedbg = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int roundedbgdark = 2130837542;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b000c
			public const int automatic = 2131427340;
			
			// aapt resource value: 0x7f0b0006
			public const int bottom = 2131427334;
			
			// aapt resource value: 0x7f0b0003
			public const int box_count = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int button = 2131427332;
			
			// aapt resource value: 0x7f0b0017
			public const int cancel_button = 2131427351;
			
			// aapt resource value: 0x7f0b0009
			public const int center = 2131427337;
			
			// aapt resource value: 0x7f0b0025
			public const int changePrefsButton = 2131427365;
			
			// aapt resource value: 0x7f0b0019
			public const int com_facebook_body_frame = 2131427353;
			
			// aapt resource value: 0x7f0b001b
			public const int com_facebook_button_xout = 2131427355;
			
			// aapt resource value: 0x7f0b0014
			public const int com_facebook_device_auth_instructions = 2131427348;
			
			// aapt resource value: 0x7f0b0013
			public const int com_facebook_device_dialog_title = 2131427347;
			
			// aapt resource value: 0x7f0b0012
			public const int com_facebook_fragment_container = 2131427346;
			
			// aapt resource value: 0x7f0b0018
			public const int com_facebook_login_activity_progress_bar = 2131427352;
			
			// aapt resource value: 0x7f0b001d
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131427357;
			
			// aapt resource value: 0x7f0b001c
			public const int com_facebook_tooltip_bubble_view_text_body = 2131427356;
			
			// aapt resource value: 0x7f0b001a
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131427354;
			
			// aapt resource value: 0x7f0b0015
			public const int confirmation_code = 2131427349;
			
			// aapt resource value: 0x7f0b000d
			public const int display_always = 2131427341;
			
			// aapt resource value: 0x7f0b0007
			public const int inline = 2131427335;
			
			// aapt resource value: 0x7f0b000f
			public const int large = 2131427343;
			
			// aapt resource value: 0x7f0b000a
			public const int left = 2131427338;
			
			// aapt resource value: 0x7f0b0020
			public const int loadingImage = 2131427360;
			
			// aapt resource value: 0x7f0b001e
			public const int loadingProgressBar = 2131427358;
			
			// aapt resource value: 0x7f0b0021
			public const int loadingProgressWheel = 2131427361;
			
			// aapt resource value: 0x7f0b0023
			public const int login_button = 2131427363;
			
			// aapt resource value: 0x7f0b0027
			public const int messenger_send_button = 2131427367;
			
			// aapt resource value: 0x7f0b000e
			public const int never_display = 2131427342;
			
			// aapt resource value: 0x7f0b0010
			public const int normal = 2131427344;
			
			// aapt resource value: 0x7f0b0000
			public const int open_graph = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int page = 2131427329;
			
			// aapt resource value: 0x7f0b0016
			public const int progress_bar = 2131427350;
			
			// aapt resource value: 0x7f0b000b
			public const int right = 2131427339;
			
			// aapt resource value: 0x7f0b0011
			public const int small = 2131427345;
			
			// aapt resource value: 0x7f0b0005
			public const int standard = 2131427333;
			
			// aapt resource value: 0x7f0b0024
			public const int synchronize_settings = 2131427364;
			
			// aapt resource value: 0x7f0b0026
			public const int textView = 2131427366;
			
			// aapt resource value: 0x7f0b0022
			public const int textView1 = 2131427362;
			
			// aapt resource value: 0x7f0b001f
			public const int textViewStatus = 2131427359;
			
			// aapt resource value: 0x7f0b0008
			public const int top = 2131427336;
			
			// aapt resource value: 0x7f0b0002
			public const int unknown = 2131427330;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int com_facebook_activity_layout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int com_facebook_device_auth_dialog_fragment = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int com_facebook_login_fragment = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int com_facebook_tooltip_bubble = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int loading = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int loadingimage = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int loadingprogress = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int Main = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int messenger_button_send_blue_large = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int messenger_button_send_blue_round = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int messenger_button_send_blue_small = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int messenger_button_send_white_large = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int messenger_button_send_white_round = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int messenger_button_send_white_small = 2130968589;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090014
			public const int ApplicationName = 2131296276;
			
			// aapt resource value: 0x7f090013
			public const int Hello = 2131296275;
			
			// aapt resource value: 0x7f090015
			public const int app_id = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int app_name = 2131296278;
			
			// aapt resource value: 0x7f090021
			public const int btn_text = 2131296289;
			
			// aapt resource value: 0x7f090001
			public const int com_facebook_device_auth_instructions = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int com_facebook_image_download_unknown_error = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int com_facebook_internet_permission_error_message = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int com_facebook_internet_permission_error_title = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int com_facebook_like_button_liked = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int com_facebook_like_button_not_liked = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int com_facebook_loading = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int com_facebook_loginview_cancel_action = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int com_facebook_loginview_log_in_button = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int com_facebook_loginview_log_in_button_long = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int com_facebook_loginview_log_out_action = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int com_facebook_loginview_log_out_button = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int com_facebook_loginview_logged_in_as = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int com_facebook_loginview_logged_in_using_facebook = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int com_facebook_send_button_text = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int com_facebook_share_button_text = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int com_facebook_tooltip_default = 2131296273;
			
			// aapt resource value: 0x7f09001d
			public const int dialog_title_edittext_preference = 2131296285;
			
			// aapt resource value: 0x7f090020
			public const int dialog_title_enum_preference = 2131296288;
			
			// aapt resource value: 0x7f090022
			public const int edittext_default_value = 2131296290;
			
			// aapt resource value: 0x7f090023
			public const int enum_preference_entry_default_value = 2131296291;
			
			// aapt resource value: 0x7f090000
			public const int library_name = 2131296256;
			
			// aapt resource value: 0x7f090012
			public const int messenger_send_button_text = 2131296274;
			
			// aapt resource value: 0x7f090018
			public const int summary_checkbox_preference = 2131296280;
			
			// aapt resource value: 0x7f09001c
			public const int summary_edittext_preference = 2131296284;
			
			// aapt resource value: 0x7f09001f
			public const int summary_enum_preference = 2131296287;
			
			// aapt resource value: 0x7f09001a
			public const int summary_switch_preference = 2131296282;
			
			// aapt resource value: 0x7f090017
			public const int title_checkbox_preference = 2131296279;
			
			// aapt resource value: 0x7f09001b
			public const int title_edittext_preference = 2131296283;
			
			// aapt resource value: 0x7f09001e
			public const int title_enum_preference = 2131296286;
			
			// aapt resource value: 0x7f090019
			public const int title_switch_preference = 2131296281;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Base_CardView = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int CardView = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int CardView_Dark = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int CardView_Light = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int MessengerButton = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int MessengerButton_Blue = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int MessengerButton_Blue_Large = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int MessengerButton_Blue_Small = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int MessengerButton_White = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int MessengerButton_White_Large = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int MessengerButton_White_Small = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int MessengerButtonText = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int MessengerButtonText_Blue = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int MessengerButtonText_Blue_Large = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int MessengerButtonText_Blue_Small = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int MessengerButtonText_White = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int MessengerButtonText_White_Large = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int MessengerButtonText_White_Small = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int com_facebook_auth_dialog = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int com_facebook_button = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int com_facebook_button_like = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int com_facebook_button_send = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int com_facebook_button_share = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int com_facebook_loginview_default_style = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int com_facebook_loginview_silver_style = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int tooltip_bubble_text = 2131230745;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int preferences = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[]
			{
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] ProgressWheel = new int[]
			{
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			public static int[] com_facebook_like_view = new int[]
			{
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 4
			public const int com_facebook_like_view_com_facebook_auxiliary_view_position = 4;
			
			// aapt resource value: 0
			public const int com_facebook_like_view_com_facebook_foreground_color = 0;
			
			// aapt resource value: 5
			public const int com_facebook_like_view_com_facebook_horizontal_alignment = 5;
			
			// aapt resource value: 1
			public const int com_facebook_like_view_com_facebook_object_id = 1;
			
			// aapt resource value: 2
			public const int com_facebook_like_view_com_facebook_object_type = 2;
			
			// aapt resource value: 3
			public const int com_facebook_like_view_com_facebook_style = 3;
			
			public static int[] com_facebook_login_view = new int[]
			{
					2130771997,
					2130771998,
					2130771999,
					2130772000};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_com_facebook_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_com_facebook_login_text = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_com_facebook_logout_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_com_facebook_tooltip_mode = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[]
			{
					2130772001,
					2130772002};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_com_facebook_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_com_facebook_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
