#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TODOList.Android.Resource", IsApplication=true)]

namespace TODOList.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Advexp.Resource.String.library_name = global::TODOList.Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_menu_refresh = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int btnAddTask = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int btnDelete = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int btnSave = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int chkDone = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int description = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int login_button = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int lstTasks = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int row = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int synchronize = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int title = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int todo_detail_layout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int todo_layout = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int home_menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int app_id = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int cancelled = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int error = 2131034122;
			
			// aapt resource value: 0x7f050011
			public const int exception = 2131034129;
			
			// aapt resource value: 0x7f050007
			public const int hello_user = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f05000e
			public const int no_friends_selected = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int no_place_selected = 2131034127;
			
			// aapt resource value: 0x7f050006
			public const int ok = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int permission_not_granted = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int photo_post = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int pick_seattle_place = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int status_update = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int success = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int successfully_posted_post = 2131034121;
			
			// aapt resource value: 0x7f050012
			public const int synchronize = 2131034130;
			
			// aapt resource value: 0x7f05000d
			public const int you_picked = 2131034125;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
